add github job

diff --git a/.github/workflows/closed_conflict_issue.yml b/.github/workflows/closed_conflict_issue.yml
--- a/.github/workflows/closed_conflict_issue.yml
+++ b/.github/workflows/closed_conflict_issue.yml
@@ -15,9 +15,13 @@ jobs:
         uses: actions/setup-python@v4
         with:
           python-version: '3.10'
+      
+      - name: Verify extract_decision.py exists
+        run: test -f human_annotations/scripts/extract_decision.py && echo "Script found." || echo "Script not found!"
 
       - name: Extract decision
         id: set-output
+        
         run: |
           pip install requests
           python human_annotations/scripts/extract_decision.py "${{ github.repository }}" "${{ github.event.issue.number }}" > decision.json
